### ISSUE TITLE
Cactus did not push 1.6.2 documentation when it was published

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#17]
**Description**
The README.md file in the root of the kivakit repository still says 1.6.1. We're now on 1.6.3-SNAPSHOT.

Let's check that the docs get published for 1.6.3 when we're ready to push that

**Comment by timboudreau** [comment]
Should already be fixed - we can verify when we do 1.6.3.

The problem was we were calling `git push` after we get the `develop` branch updated with the new snapshot version.  We should have been calling `git push --all` - that was the intent in the release profile - so that `release/current` and `release/n.n.n` _all_ got pushed.

I fixed that in the profile last week.
