### ISSUE TITLE
kivakit-extensions GitHub build fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#46]
for details, see:

```
https://github.com/Telenav/kivakit-extensions/runs/7981468602?check_suite_focus=true

**Comment by jonathanl-telenav** [comment]
this bug blocks our dev process

**Comment by timboudreau** [comment]
Probably we should just turn the cactus tests off for these builds, since they are irrelevant to what it's trying to build.

But first it would be good to track down the failure, so I added a variant of `build-branch.yml` in `telenav-github` that will run the cactus tests with full debug output and [switched the action for kivakit-extensions to use that](https://github.com/Telenav/kivakit-extensions/commit/a1b1e85d9c219c85a8ee4aac8a17eb6918a7ca5a)

**Comment by timboudreau** [comment]
Fixed.
