### ISSUE TITLE
missing submodule

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#55]
the maven command:

`mvn -Dorg.slf4j.simpleLogger.logFile="/var/folders/rm/1qd3sg1n6gx12kbf39xgp73w0000gn/T/maven-Thu-2022.07.31-11.49-telenav-checkout.log" -Dorg.slf4j.simpleLogger.defaultLogLevel="info" -Dorg.slf4j.simpleLogger.cacheOutputStream=false -Dcactus.fetch-first=true -Dcactus.base-branch=develop -Dcactus.target-branch="feature/cors2" -Dcactus.update-root=true -Dcactus.include-root=true -Dcactus.create-branches=true -Dcactus.create-local-branches=true -Dcactus.push=false -Dcactus.permit-local-changes=true -Dcactus.scope=all com.telenav.cactus:cactus-maven-plugin:1.5.26:checkout validate 2>&1`

produces this missing submodule error:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.393 s
[INFO] Finished at: 2022-08-31T11:49:48-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.telenav.cactus:cactus-maven-plugin:1.5.26:checkout (default-cli) on project safety-service-uber-bom: java.lang.IllegalArgumentException: Missing submodule -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :safety-service-uber-bom

**Comment by jonathanl-telenav** [comment]
it did switch branches.

**Comment by jonathanl-telenav** [comment]
i am adding cactus and lexakai-* to the safety-service-build workspace, so it probably has something to do with that?

**Comment by timboudreau** [comment]
You have to use 'git submodule add' and init it - so git does the checkout for you and updates the metadata in .git. otherwise, if you just check it out, and add something to .gitmodules, it will not understand what it is looking at.

I gave you a branch with a complete working set of poms you could have just used, which solved your cactus build problem - did you read or try any of the instructions I sent you?

It doesn't seem great to add clutter here.

**Comment by timboudreau** [comment]
In short, if you want to add a git submodule, DO NOT CHECK ANYTHING OUT UNDER THE WORKSPACE.

Just run

git submodule add -b $BRANCH $REPO
git submodule init
git submodule update

and NOTHING else and it will with.

But as I said before - just use the safety-service poms from the uberbuild branch and you won't have any conflicts because of cactus.

**Comment by timboudreau** [comment]
What it looks like is, you had a checkout that had not had one of `git submodule init` or `git submodule update` run on it since some remote modules were added.

So, git knows they are supposed to be there, but they haven't actually been checked out into your working tree.  A lot of things (anything that calls `git submodule foreach`, for example) is going to fail under those circumstances.  There is not really anything I can do about it.  I suppose every single mojo could try to determine if there are missing submodules and give a better error message, but it's a pretty rare condition and would add a bunch of overhead to every command that does anything with git - any of which could fail if stuff that's supposed to be there isn't.

**Comment by jonathanl-telenav** [comment]
I added this information to the markdown help for developers.
